name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: huggingface/hub-sync@v1
        with:
          github_repo_id: Merongetachew/MGspeed
          huggingface_repo_id: Merongetachew/MGspeed
          repo_type: space
          space_sdk: docker
          hf_token: ${{ secrets.HF_TOKEN }}
